package com.nike.backstopper.exception;

import com.nike.backstopper.model.AutoGeneratedApiError;

/**
 * This exception is used to signal {@link AutoGeneratedApiError#getMessage()} mapping issues.
 *
 * @author Andrey Tsarenko
 */
public class ApiErrorValidationMessagesMapperException extends RuntimeException {

    public ApiErrorValidationMessagesMapperException(String message, Throwable cause) {
        super(message, cause);
    }

}
