package com.nike.backstopper.exception;

import com.nike.backstopper.model.AutoGeneratedApiError;

/**
 * This exception is used to signal {@link AutoGeneratedApiError} finding issues.
 *
 * @author Andrey Tsarenko
 */
public class AutoGeneratedApiErrorServiceException extends RuntimeException {

    public AutoGeneratedApiErrorServiceException(String message, Throwable cause) {
        super(message, cause);
    }

}
