package com.nike.backstopper.model;

import com.nike.backstopper.util.ApiErrorUtil;
import org.junit.Test;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Tests the functionality of {@link AutoGeneratedApiError}.
 *
 * @author Andrey Tsarenko
 */
public class AutoGeneratedApiErrorTest {

    @Test
    public void getters() {
        AutoGeneratedApiError autoGeneratedApiError = new AutoGeneratedApiError("message", "errorCode", 400);

        assertThat(autoGeneratedApiError.getErrorCode()).isEqualTo("errorCode");
        assertThat(autoGeneratedApiError.getHttpStatusCode()).isEqualTo(400);
        assertThat(autoGeneratedApiError.getMessage()).isEqualTo("message");
    }

    @Test
    public void equals() {
        AutoGeneratedApiError firstAutoGeneratedApiError = new AutoGeneratedApiError("message", "errorCode", 400);
        AutoGeneratedApiError secondAutoGeneratedApiError = new AutoGeneratedApiError("message", "errorCode", 400);
        AutoGeneratedApiError thirdAutoGeneratedApiError = new AutoGeneratedApiError("message", "secondErrorCode", 400);

        assertThat(firstAutoGeneratedApiError).isEqualTo(firstAutoGeneratedApiError);
        assertThat(firstAutoGeneratedApiError).isEqualTo(secondAutoGeneratedApiError);

        assertThat(firstAutoGeneratedApiError).isNotEqualTo(thirdAutoGeneratedApiError);
        assertThat(firstAutoGeneratedApiError).isNotEqualTo(new Object());
        assertThat(firstAutoGeneratedApiError).isNotEqualTo(null);
    }

    @Test
    public void hashcode() {
        AutoGeneratedApiError autoGeneratedApiError = new AutoGeneratedApiError("message", "errorCode", 400);

        assertThat(autoGeneratedApiError.hashCode()).isEqualTo(
                ApiErrorUtil.generateApiErrorHashCode(autoGeneratedApiError));
    }

}
