name: Build

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      - name: Validate Gradle Wrapper Checksums
        uses: gradle/actions/wrapper-validation@v3
      - name: Build with Gradle
        run: ./gradlew clean build
      - name: Upload coverage report to CodeCov
        uses: codecov/codecov-action@v4
        with:
          files: build/reports/jacoco/jacocoRootReport/jacocoRootReport.xml
          fail_ci_if_error: true
          verbose: true
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Upload reports and test results to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: reports-and-test-results
          path: |
            build/reports/
            build/test-results/
